version: '3.5'

services: 
  mongo-container:
    container_name: mongo-container
    build: ./database/
    volumes:
      - ./database/data:/data/db
    ports:
      - "27017:27017"
    networks:
      testing_net:
            ipv4_address: 182.18.7.5


  servidor1:
    container_name: servidor1
    build: ./server/
    env_file: .env
    ports: 
      - '3001:3001'
    networks:
      testing_net:
            ipv4_address: 182.18.7.6

networks:
  testing_net:
      ipam:
          driver: default
          config:
              - subnet: 182.18.7.0/24



