version: '3.5'

services: 
  mongo-container:
    container_name: mongo-container
    image: mongo:latest
    volumes:
      - ./dataMongo:/data/db
    ports:
      - "27017"
    networks:
      db_network:
        ipv4_address: 10.10.13.10

  servidor1:
    container_name: servidor1
    build: ./server/
    env_file: .env
    ports: 
      - '3001:3001'
    environment: 
      CARNET_1: "201020126"
    networks:
      service_network:
        ipv4_address: 172.35.73.10
      db_network:
        ipv4_address: 10.10.13.20
  
  servidor2:
    container_name: servidor2
    build: ./server2/
    env_file: .env
    ports: 
      - '3002:3002'
    environment: 
      CARNET_2: "201503600"
    networks:
      service_network:
        ipv4_address: 172.35.73.20
      db_network:
        ipv4_address: 10.10.13.30

networks:
  db_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.13.0/24

  service_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.35.73.0/24



