version: '3.5'

services: 
  mongo-container:
    container_name: mongo-container
    build: ./database/
    volumes:
      - ./database/data:/data/db
    ports:
      - "27017"
    networks:
      db_network:
        ipv4_address: 10.10.13.10

  servidor1:
    container_name: servidor1
    build: ./server/
    env_file: .env
    ports: 
      - '3001:3001'
    networks:
      service_network:
        ipv4_address: 172.35.73.10
      db_network:
        ipv4_address: 10.10.13.20

networks:
  db_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.13.0/24

  service_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.35.73.0/24



