version: '3.5'

services: 
  mongo-container:
    container_name: mongo-container
    build: ./database/
    volumes:
      - ./database/data:/data/db
    ports:
      - "27017:27017"

  servidor1:
    container_name: servidor1
    build: ./server/
    env_file: .env
    ports: 
      - '3001:3001'




