version: '3.5'

services: 

  servidor1:
    container_name: servidor1
    build: ./server/
    env_file: .env
    ports: 
      - '3001:3001'


  mongo-container:
    container_name: mongo-container
    image: mongo:latest
    volumes:
      - ./datebase/data:/data/db
    ports:
      - "27017:27017"
    restart: on-failure

