version: '3.5'

services: 
  mongo-container:
    container_name: mongo-container
    image: mongo:latest
    volumes:
<<<<<<< HEAD
      - /dataMongo:/data/db
=======
      - /home/dataMongo:/data/db
>>>>>>> 6221db1eb1e8faffa2c4ecb40a7483d2be53d809
    ports:
      - "27017"
    networks:
      db_network:
        ipv4_address: 10.10.13.10

  servidor1:
    container_name: servidor1
    build: ./server/
<<<<<<< HEAD
    ports: 
      - '3001:3001'
    environment: 
      PORT_1: 3001
      CARNET_1: "201020126"
=======
    entrypoint: env
    environment: 
      PORT_1: "${PORT_1}"
      CARNET_1: "${CARNET_1}"
    ports: 
      - '3002:3002'
>>>>>>> 6221db1eb1e8faffa2c4ecb40a7483d2be53d809
    networks:
      service_network:
        ipv4_address: 172.35.73.10
      db_network:
        ipv4_address: 10.10.13.20
  
  servidor2:
    container_name: servidor2
    build: ./server2/
    ports: 
<<<<<<< HEAD
      - '3002:3002'
    environment: 
      PORT_1: 3002
=======
      - '3003:3003'
    environment: 
      PORT_2: 3003
>>>>>>> 6221db1eb1e8faffa2c4ecb40a7483d2be53d809
      CARNET_2: "201503600"
    networks:
      service_network:
        ipv4_address: 172.35.73.20
      db_network:
        ipv4_address: 10.10.13.30

  servidor3:
    container_name: servidor3
    build: ./server3/
    ports: 
<<<<<<< HEAD
      - '3003:3003'
    environment: 
      PORT_1: 3003
=======
      - '3004:3004'
    environment: 
      PORT_3: 3004
>>>>>>> 6221db1eb1e8faffa2c4ecb40a7483d2be53d809
      CARNET_3: "201504231"
    networks:
      service_network:
        ipv4_address: 172.35.73.30
      db_network:
        ipv4_address: 10.10.13.40

<<<<<<< HEAD
=======
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - servidor1
      - servidor2
      - servidor3
    ports:
      - "3001:3001"
    networks:
      service_network:
        ipv4_address: 172.35.73.40

>>>>>>> 6221db1eb1e8faffa2c4ecb40a7483d2be53d809
networks:
  db_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.13.0/24

  service_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.35.73.0/24



